//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Staging_DxFremontProductInfoEntities : DbContext
    {
        public Staging_DxFremontProductInfoEntities()
            : base("name=Staging_DxFremontProductInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_TPL_ProductPrice> vw_TPL_ProductPrice { get; set; }
        public virtual DbSet<vw_TPL_TotalGPCR> vw_TPL_TotalGPCR { get; set; }
        public virtual DbSet<vw_TPL_CellBasedKinase> vw_TPL_CellBasedKinase { get; set; }
        public virtual DbSet<vw_TPL_Assays> vw_TPL_Assays { get; set; }
        public virtual DbSet<vw_TPL_Synergy> vw_TPL_Synergy { get; set; }
    }
}
