//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public string ContractID { get; set; }
        public string QuoteID { get; set; }
        public string Product { get; set; }
        public string NumberOfCompounds { get; set; }
        public string NumberOfAssays { get; set; }
        public string PricePerInteraction { get; set; }
        public string TotalPrice { get; set; }
        public string BillingTerms { get; set; }
        public string PONumber { get; set; }
        public string DateSigned { get; set; }
        public string DateExpires { get; set; }
        public string DateCompleted { get; set; }
        public string ContactName { get; set; }
        public string AssigneeName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string DistributionList { get; set; }
        public string Comments { get; set; }
        public string OrderStatus { get; set; }
        public string ReportFormat { get; set; }
        public string RevenueClass { get; set; }
        public string Redundancy { get; set; }
        public string PublishStatus { get; set; }
        public string Address2 { get; set; }
        public string BillingAddress { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingStateProvince { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingDistribution { get; set; }
        public string Address3 { get; set; }
        public string BillingAddress3 { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardType { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardExpDate { get; set; }
        public string CreditCardCode { get; set; }
        public string GetSignedDate { get; set; }
        public string NumberOfConcentrations { get; set; }
        public string MaterialsCost { get; set; }
        public string SalesID { get; set; }
    }
}
