//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dx_Request
    {
        public int Dx_RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequestContactID { get; set; }
        public int AssigneeID { get; set; }
        public int NumberOfCompounds { get; set; }
        public Nullable<int> RequestStatusID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.Guid> WebRequestID { get; set; }
        public string Note { get; set; }
        public Nullable<bool> RequestCompleted { get; set; }
        public string Experiment { get; set; }
        public Nullable<int> NumberOfInteractions { get; set; }
        public Nullable<decimal> PricePerInteraction { get; set; }
        public Nullable<decimal> DiscountPerInteraction { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> PriceKdFollowUp { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> QuoteExpiresDate { get; set; }
        public Nullable<bool> QuoteActive { get; set; }
        public string QuoteContent { get; set; }
        public byte[] QuoteImage { get; set; }
        public Nullable<decimal> Concentration { get; set; }
        public string QuoteComment { get; set; }
        public string OrderNotes { get; set; }
        public Nullable<int> dupl_singl { get; set; }
        public string actions { get; set; }
        public Nullable<int> RequestSourceID { get; set; }
        public string QuoteNumber { get; set; }
        public Nullable<int> ContractExists { get; set; }
        public bool Is_Custom { get; set; }
        public int Number_Of_Custom_Targets { get; set; }
        public int Number_Of_Custom_Modes { get; set; }
        public int Number_Of_Predefined_Panels { get; set; }
        public bool Is_Single_Point { get; set; }
        public int Number_Of_Single_Point_Concentrations { get; set; }
        public string mtCreatedBy { get; set; }
        public Nullable<System.DateTime> mtCreatedDate { get; set; }
        public string mtLastModifiedBy { get; set; }
        public Nullable<System.DateTime> mtLastModifiedDate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> CurrencyExchangeRate { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public Nullable<decimal> ShippingSurchargePercent { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public int Number_Of_Dose_Response_Concentrations { get; set; }
        public Nullable<decimal> MaterialsCost { get; set; }
        public string SalesID { get; set; }
    }
}
