//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KinomeScan_RequestManagerEntities : DbContext
    {
        public KinomeScan_RequestManagerEntities()
            : base("name=KinomeScan_RequestManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dx_Request> Dx_Request { get; set; }
    
        public virtual ObjectResult<mtp_Dx_RequestAssaysSelect_Result> mtp_Dx_RequestAssaysSelect(Nullable<int> dx_RequestID)
        {
            var dx_RequestIDParameter = dx_RequestID.HasValue ?
                new ObjectParameter("Dx_RequestID", dx_RequestID) :
                new ObjectParameter("Dx_RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mtp_Dx_RequestAssaysSelect_Result>("mtp_Dx_RequestAssaysSelect", dx_RequestIDParameter);
        }
    }
}
