//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string AmbitOrderID { get; set; }
        public string QuoteID { get; set; }
        public string OrderIDType { get; set; }
        public string Company { get; set; }
        public string ProfilingSet { get; set; }
        public string NumberOfCompounds { get; set; }
        public string NumberOfAssays { get; set; }
        public string NumberOfKds { get; set; }
        public string NumberOfTargets { get; set; }
        public string NumberOfReplicates { get; set; }
        public string NumberOfConcentrations { get; set; }
        public string NumberOfPlates { get; set; }
        public string PercentComplete { get; set; }
        public string RequestDate { get; set; }
        public string ReceivedDate { get; set; }
        public string DueDate { get; set; }
        public string SeedDate { get; set; }
        public string TargetDate { get; set; }
        public string CompletedDate { get; set; }
        public string ScreeningStatus { get; set; }
        public string Assignee { get; set; }
        public string OrderFolder { get; set; }
        public string Comments { get; set; }
        public string Priority { get; set; }
        public string RunID { get; set; }
        public string SeedEndDate { get; set; }
    }
}
