//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TPL_Assays
    {
        public long ID { get; set; }
        public string BasePartNumber { get; set; }
        public string CellBkgdNumber { get; set; }
        public string TARGET { get; set; }
        public string Assay_Type { get; set; }
        public string Brands { get; set; }
        public string DESCRIPTION { get; set; }
        public string CellLinePN { get; set; }
        public string ExpressKitPN { get; set; }
        public string CellPoolPN { get; set; }
        public string Assay_Readout { get; set; }
        public string Assay_Measures { get; set; }
        public string Web_Target_Class { get; set; }
        public string PROF_COMMERCIAL_NAME_PANEL { get; set; }
        public string PROF_COMMERCIAL_NAME_PRIMARY_ELECT { get; set; }
        public string MouseOrtholog { get; set; }
        public string RatOrtholog { get; set; }
        public string SimianOrtholog { get; set; }
        public string CanineOrtholog { get; set; }
        public string DateAdded { get; set; }
        public string CellBackGround { get; set; }
        public string GenBankAccessionNumber { get; set; }
        public string Ligand { get; set; }
        public string Family { get; set; }
        public string Product_Type { get; set; }
    }
}
