//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TPL_TotalGPCR
    {
        public long ID { get; set; }
        public string Family { get; set; }
        public string CommonName { get; set; }
        public string TARGET { get; set; }
        public string ArrestinCellLineMouseOrtholog { get; set; }
        public string ArrestinCellLineRatOrtholog { get; set; }
        public string ArrestinCellLineCanineOrtholog { get; set; }
        public string ArrestinCellLineSimianOrtholog { get; set; }
        public string ArrestinKitsMouseOrtholog { get; set; }
        public string ArrestinKitsRatOrtholog { get; set; }
        public string ArrestinKitsCanineOrtholog { get; set; }
        public string ArrestinKitsSimianOrtholog { get; set; }
        public string ArrestinCellLines { get; set; }
        public string ArrestinKits { get; set; }
        public string cAMPCellLines { get; set; }
        public string cAMPKits { get; set; }
        public string cAMPCellLineMouseOrtholog { get; set; }
        public string cAMPKitMouseOrtholog { get; set; }
        public string cAMPCellLineRatOrtholog { get; set; }
        public string cAMPKitRatOrtholog { get; set; }
        public string cAMPCellLineSimianOrtholog { get; set; }
        public string cAMPKitSimianOrtholog { get; set; }
        public string cAMPCellLineCanineOrtholog { get; set; }
        public string cAMPKitCanineOrtholog { get; set; }
        public string cAMPReadout { get; set; }
        public string InternalizationCellLines { get; set; }
        public string InternalizationKits { get; set; }
        public string ABHunterFunctionalKits { get; set; }
        public string ABHunterBindingKits { get; set; }
        public string PathHunterKits { get; set; }
        public string CALCIUMKits { get; set; }
        public string AN_Target_Class { get; set; }
        public string Web_Target_Class { get; set; }
        public string Assay_Measures { get; set; }
        public string AbHunterKit { get; set; }
        public string LeadHunterServiceMax { get; set; }
        public string LeadHunterServiceProfiling { get; set; }
        public string cAMPProfiling { get; set; }
        public string CalciumProfiling { get; set; }
        public string CalciumCellLine { get; set; }
        public string Coupling { get; set; }
    }
}
