//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TPL_Synergy
    {
        public string GroupID { get; set; }
        public string PartNumber { get; set; }
        public string CoreNumber { get; set; }
        public string TARGET { get; set; }
        public string ProductCategory { get; set; }
        public string LigandPartNumber { get; set; }
        public string LigandDescription { get; set; }
        public string CellCultureKit { get; set; }
        public string CellPlatingReagent { get; set; }
        public string DetectionReagents { get; set; }
        public string ReviveMedia { get; set; }
        public string PreserveFreezingReagent { get; set; }
        public string CellProliferationKit { get; set; }
        public string LDHQuantificationKit { get; set; }
        public string GlutathionQuantificationKit { get; set; }
        public string DNADamageQuantificationKit { get; set; }
    }
}
