//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discoverx.Models.CBIS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TPL_CellBasedKinase
    {
        public long ID { get; set; }
        public string Family { get; set; }
        public string CommonName { get; set; }
        public string TARGET { get; set; }
        public string DESCRIPTION { get; set; }
        public string CellLines { get; set; }
        public string ExpressKits { get; set; }
        public string InternalizationCellLines { get; set; }
        public string InternalizationKits { get; set; }
        public string ABHunterFunctionalKits { get; set; }
        public string ABHunterBindingKits { get; set; }
        public string PathHunterKits { get; set; }
        public string AN_Target_Class { get; set; }
        public string Web_Target_Class { get; set; }
        public string AbHunterKit { get; set; }
        public string LeadHunterServiceMax { get; set; }
        public string LeadHunterServiceProfiling { get; set; }
        public string PartnerProtein { get; set; }
    }
}
